"""add color to notes

Revision ID: 645e5cede571
Revises: d32599368a25
Create Date: 2026-10-05 00:01:39.680952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645e5cede571'
down_revision: Union[str, Sequence[str], None] = 'd32599368a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "notes",
        sa.Column(
            "color",
            sa.String(length=50),
            nullable=False,
            server_default="yellow",
        ),
    )

    op.alter_column(
        "notes",
        "color",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'color')
    # ### end Alembic commands ###
